server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer
            uri: lb://CUSTOMER
            predicates:
              - Path=/api/v1/customers/**
            filters:
              - AddResponseHeader=X-Powered_by,Migeri Gateway Service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka