server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fraud
    username: root
    password: secret
    jpa:
      hibernate:
        ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true